In [2]:
#program to print"Hello world"
print("Hello world")

Hello world


In [3]:
#types expressions and variables string operations
a=10;
print(type(a))

<class 'int'>


In [4]:
b=10.2;
print(type(b))

<class 'float'>


In [5]:
a="ABC";
print(type(a))

<class 'str'>


In [8]:
a=True;
print(type(a))

<class 'bool'>


In [11]:
#string operations
#printing a string
str="Hello v"
print(str)


Hello v


In [12]:
#string slicing
str="Hello"
print(str)
print(str[0])
print(str[0:3])
print(str[0:])

Hello
H
Hel
Hello


In [2]:
#string concatenation
a="Hello"
b="world"
print("a+b=",a+b)
print("a*3=",a*3)

a+b= Helloworld
a*3= HelloHelloHello


In [22]:
#membership function
a="Hello"
"b" in a

False

In [23]:
"o" in a

True

In [24]:
#capitalize() (string starting letter becomes capital)
a="Hello"
a.capitalize()


'Hello'

In [25]:
#case fold() (all letters converted to small)
a="HELLO"
a.casefold()


'hello'

In [26]:
#count() (gives the count of given substring)
a="Data Science"
a.count('e')


2

In [28]:
#index() (gives the index of a given substring)
a="Data Science"
a.index("a")

1

In [32]:
#isalpha() (gives true if the given string isalpha)
a="DataScience"
a.isalpha()

True

In [33]:
#join() (can join two strings)
a="abc"
b="cde"
a.join(b)

'cabcdabce'

In [34]:
#partition() (it can divide the given string into 3 parts)
a="Data Science"
a.partition("a")


('D', 'a', 'ta Science')

In [41]:
#find() (gives the index of the given substring)
a="Data Science"
a.find('t')


2

In [42]:
#replace() (replace one value with another)
a="Bata science"
a.replace("B","D")


'Data science'

In [65]:
#python datastructures:lists and tuples sets,and dictionaries
#list operations
#printing the list
L=(["ABC","DEF"])
L

['ABC', 'DEF']

In [66]:
L=[1,2,3,4]
L

[1, 2, 3, 4]

In [67]:
#Append() (append the required list at the end)
L=[1,2,3]
L.append([9,7])
L

[1, 2, 3, [9, 7]]

In [68]:
#insert() (To insert the input at the given index)
L=[1,2,3,4]
L.insert(0,2)
L

[2, 1, 2, 3, 4]

In [101]:
#Accessing the list elements
l=[1,2,3,4]
l[0]


1

In [99]:
l[-1]

4

In [105]:
#extend()(to extend the list)
l=[1,2,3,4]
l.extend([9,8])
l

[1, 2, 3, 4, 9, 8]

In [104]:
#deleting the element del()
l=[1,2,3,4]
del(l[0])
l

[2, 3, 4]

In [106]:
#pop() (delete the last element)
l=[1,2,3,4]
l.pop()
l

[1, 2, 3]

In [107]:
#reverse() (to reverse the list)
l=[1,2,3,4]
l.reverse()
l

[4, 3, 2, 1]

In [109]:
#add() (to add to lists)
l1=[1,2,3]
l2=["a","b"]
(l1+l2)

[1, 2, 3, 'a', 'b']

In [110]:
#sort() (to sort the elements in ascending order)
l=[1,8,3,4]
l.sort(reverse=True)
l

[8, 4, 3, 1]

In [111]:
#len() (to get the length of list)
l=[1,2,3,4]
len(l)

4

In [116]:
#max() ( to get the maximum value)
l=[1,2,3,4]
max(l)

4

In [117]:
min(l)

1

In [118]:
#tuple operations
#printing tuple
t=(1,2,3,4)
t

(1, 2, 3, 4)

In [119]:
#length() (to get length of the tuple)
t=(1,2,3,4)
len(t)

4

In [120]:
#count() (to get the count of the given element)
t=(1,2,3,4,3,3)
t.count(3)


3

In [121]:
#index() (to get index of the given element)
t=(1,2,3,4)
t.index(2)


1

In [122]:
#set operations
#creating set
s={1,2,3}
s

{1, 2, 3}

In [123]:
#union() (to combine two sets)
s1={1,2,3}
s2={4,5,6}
s1.union(s2)

{1, 2, 3, 4, 5, 6}

In [124]:
#intersection() ( to get the common elements in 2 sets)
s1={1,2,3}
s2={2,4,5}
s1.intersection(s2)

{2}

In [125]:
#set difference() (to get the different element)
s1={1,2,3}
s2={2,3,4}
s1.difference(s2)


{1}

In [126]:
#update and delete (to delete & update elements)
s={0,1,2,3}
s.add(4)
s


{0, 1, 2, 3, 4}

In [127]:
#clear() (to clear the set)
s={0,1,2}
s.clear()
s

set()

In [132]:
#pop() (to pop (del) 1st element)
s={0,1,2}
s.pop()


0

In [134]:
#discard() (to delete the given)
s={0,1,2}
s.discard(0)
s

{1, 2}

In [137]:
#copy() (to copy the set to another set)
s1={0,1,2}
s1.copy()

{0, 1, 2}

In [140]:
#set difference update() (difference updated)
s={1,2,3}
s.difference_update({3})
s

{1, 2}

In [159]:
#intersection update()
s1={1,2,3}
s1.difference_update()
s1.intersection_update({8},{1})

In [170]:
#disjoint()
s1={1,2,3}
s2={1,4,8,9}
s1.isdisjoint(s2)

False

In [168]:
#is superset()
s1={1,2,3}
s2={1,4,8,9}
s1.issuperset(s2)

False

In [171]:
s1.issubset(s2)

False

In [172]:
#dictionaries operations
#creating dictionary
d={"name":"priya","rno":126}
d

{'name': 'priya', 'rno': 126}

In [183]:
d["name"]="ravali"
d

{'name': 'ravali', 'rno': 126}

In [6]:
#program to find greatest number among 3 numbers using if condition
a=int(input("enter the number1:"))
b=int(input("enter the number2:"))
c=int(input("enter the number3:"))
if a>b and a>c:
    print("a is greatest number")
if b>a and b>c:
        print("b is greatest number")
if c>a and c>b:
        print("c is greatest number")

enter the number1:3
enter the number2:4
enter the number3:5
c is greatest number


In [8]:
a=int(input("enter the number rather than 0:"))
if a>0:
    print("given number is positive")
else:
    print("given number is negative")

enter the number rather than 0:4
given number is positive


In [11]:
n=int(input("enter the number:"))
for i in range(1,n,1):
    print(i)

enter the number:4
1
2
3


In [12]:
#reverse the numbers
n=int(input("enter the number:"))
for i in range(n,0,-1):
    print(i)

enter the number:4
4
3
2
1


In [13]:
n=int(input("enter the number:"))
f=1
for i in range(1,n+1):
    f=f*i
print(f)

enter the number:4
24


In [14]:
n=int(input("enter the number:"))
i=0
while(i<=n):
    print(i)
    i=i+1
    

enter the number:4
0
1
2
3
4


In [16]:
def display():
    print("hello world")
display()

hello world


In [18]:
n=int(input("enter the number"))
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    print(f)
fact(n)

enter the number4
24


In [23]:
#factorial using functions 
def fact(n):
    f=1
    for i in range(1,n+1):
        f=f*i
    return f
n=int(input("enter the number"))
y=fact(n)
print(y)

enter the number4
24


In [25]:
#power of a number
n=int(input("enter the number"))
x=int(input("enter the number"))
def power(x,n):
    if n==0:
        return 1
    else:
        return(x*pow(x,n-1))
print(power(x,n))

enter the number3
enter the number2
8


In [16]:
# object and classes
class student
a=10
obj=student()
print(obj.a)

SyntaxError: invalid syntax (<ipython-input-16-57654b48a20f>, line 2)

In [53]:
class student(object):
    def-init-(selfname,rno)
    self.name=name
    self.rno
    def display(self)
    print(self.name)
    print(self.rno)
    s1=student("v",1)
    s1.display()
    s2=student("jk",2)
    s2.display()

SyntaxError: invalid syntax (<ipython-input-53-2f11bde2be6e>, line 2)

In [5]:
#reading files with open,writing files with open 
f=open("f1.txt","w")
f.write("Hi")
f=open("f1.txt","r")
f.read()
f.close()

In [7]:
#Append()
f=open("f1.txt","w")
f.write("hello")
f=open("f1.txt","a")
#f.append("world")
f=open("f1.txt","r")
f.read()
f.close()

In [8]:
#Reading the files
f=open("f1.txt","w")
f.write("hello world")
f.close()
f=open("f1.txt","r")
f.readline()
f.read(10)
f.close()

In [9]:
#tell() (to know the curser location)
f=open("f1.txt","w")
f.write("hello world")
#f.open("f1.txt","r")
f.tell()
f.close()

In [10]:
#seek() (to change the cursor position)
f=open("f1.txt","w")
f.write("hello world")
f.seek(10,0)
f.close()

In [11]:
#PANDAS 
import pandas as pd
d=[1,2,3]
a=pd.Series(d)
a
b=pd.Series(["hello","hi"])
b

0    hello
1       hi
dtype: object

In [12]:
#Data frame
df={"name":pd.Series([1,2,3]),"rno":pd.Series([0,1,2])}
df=pd.DataFrame(df)
df

name  rno
0     1    0
1     2    1
2     3    2

In [32]:
#Reading data from  the file
a=pd.read_csv("bollywood.csv")
a

SlNo Release Date                    MovieName ReleaseTime      Genre  \
0       1    18-Apr-14                     2 States          LW    Romance   
1       2     4-Jan-13                 Table No. 21           N  Thriller    
2       3    18-Jul-14           Amit Sahni Ki List           N     Comedy   
3       4     4-Jan-13             Rajdhani Express           N     Drama    
4       5     4-Jul-14                 Bobby Jasoos           N     Comedy   
..    ...          ...                          ...         ...        ...   
144   145    27-Feb-15           Dum Laga Ke Haisha           N     Comedy   
145   146    13-Mar-15                         NH10           N   Thriller   
146   147    20-Mar-15  Dilliwali Zaalim Girlfriend           N     Comedy   
147   148    20-Mar-15                     Hunterrr           N     Comedy   
148   149    23-May-14                Kochadaiiyaan          HS     Action   

     Budget  BoxOfficeCollection  YoutubeViews  YoutubeLikes  YoutubeDislikes  
0        36               104.00       8576361         26622             2527  
1        10                12.00       1087320          1129              137  
2        10                 4.00        572336           586               54  
3         7                 0.35         42626            86               19  
4        18                10.80       3113427          4512             1224  
..      ...                  ...           ...           ...              ...  
144      15                30.00       3250917          8185              615  
145      13                32.10       5592977         15464             1513  
146      32                12.00       2316047          4289              807  
147       5                11.89       4674795          3706              762  
148     150               120.00       4740727         13466             2649  

[149 rows x 10 columns]

In [35]:
#to retrieve the column in the given data frame
df.columns

Index(['name', 'rno'], dtype='object')

In [36]:
#type(to get the type of the input)
type(df)

pandas.core.frame.DataFrame

In [37]:
#size (to get the size of the data frame)
df.size

6

In [40]:
#shape( to get the shape of the data frame)
df.shape

(3, 2)

In [41]:
#info() ( to get the complete information about the dataframe)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
name    3 non-null int64
rno     3 non-null int64
dtypes: int64(2)
memory usage: 176.0 bytes


In [42]:
#is null()( to get the null values)
df.isnull()

name    rno
0  False  False
1  False  False
2  False  False

In [43]:
#is null().sum() ( to get the no of null values)
df.isnull().sum()

name    0
rno     0
dtype: int64

In [44]:
#head() (to get the first 5 values)
df.head()

name  rno
0     1    0
1     2    1
2     3    2

In [47]:
#tail() to get the last 5 rows
df.tail(1)

name  rno
2     3    2

In [48]:
#describe() ( to get the aggregate values of numerical column)
df.describe()

name  rno
count   3.0  3.0
mean    2.0  1.0
std     1.0  1.0
min     1.0  0.0
25%     1.5  0.5
50%     2.0  1.0
75%     2.5  1.5
max     3.0  2.0

In [51]:
# to get the specific row:

df[0:3]

name  rno
0     1    0
1     2    1
2     3    2

In [52]:
#to get the required columns
df.columns[0:3]

Index(['name', 'rno'], dtype='object')

In [56]:
# to get the single column all values
df["name"]

0    1
1    2
2    3
Name: name, dtype: int64

In [74]:
# iloc[] to get the specified rows and columns
df.iloc[:,:]

name  rno
0     1    0
1     2    1
2     3    2

In [80]:
#to get the random columns:
df.iloc[1:2,[1.2]]

rno
1    1

In [14]:
#working with numpy arrays: numpy 1d arrays,numpy 2d array
# 1-D array
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [15]:
#(rows and columns)
a.shape

(3,)

In [16]:
#( to get dimensions of an array)
a.ndim

1

In [17]:
#(to get total number of elements)
a.size

3

In [18]:
#1-D operations
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)

[-3 -3 -3]


In [19]:
print(a+b)

[5 7 9]


In [20]:
print(a*b)

[ 4 10 18]


In [21]:
#abs() to get the absolute values
a=np.array([1.2,10.3,4])
np.abs(a)

array([ 1.2, 10.3,  4. ])

In [22]:
#sort() to sort the given array in ascending order
a=np.array([50,10,1,4,2])
np.sort(a)

array([ 1,  2,  4, 10, 50])

In [23]:
#to sort in descending order
np.sort(a)[::-1]

array([50, 10,  4,  2,  1])

In [24]:
#ones() to get 1 dimensional ones array
np.ones(4)

array([1., 1., 1., 1.])

In [25]:
#zeros() to get 1 d zeroes array
np.zeros(3)

array([0., 0., 0.])

In [26]:
#aggregate functions
a=np.array([1,2,3,4])
np.sum(a)

10

In [27]:
np.max(a)

4

In [28]:
np.min(a)

1

In [29]:
np.mean(a)

2.5

In [30]:
np.median(a)

2.5

In [31]:
#arange() to arange the given numbers with givenspace
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [32]:
#linspace() to divide the given range into given no of equal parts

a=np.linspace(0,20,3)

In [33]:
#unique() gives the unique numbers in the given array
a=np.array([1,2,1,2])
np.unique(a)

array([1, 2])

In [34]:
#random() to generate random array
np.random.randint(0,10,10)

array([5, 4, 1, 3, 9, 2, 8, 5, 6, 1])

In [35]:
#random.seed() to get the same random values
np.random.seed(7)
np.random.randint(0,10,3)

array([4, 9, 6])

In [36]:
#2-D array

a=np.zeros([3,2])
a


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
a=np.ones([2,2])
a

array([[1., 1.],
       [1., 1.]])

In [38]:
np.random.choice([1,3,2],size=(3,2))

array([[1, 3],
       [2, 1],
       [3, 2]])

In [39]:
a=np.array(([1,2,3],[4,5,6],[7,8,9]))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a=np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.add(a,b)

array([5, 7, 9])